### ISSUE TITLE
Not working  mounting blue ray as usb000

### ISSUE THREAD

**Issue by ranjithran** [PS3Xploit/han-autoxml-template#3]
I used bf4 dic to mount not working and another issue is usb as bdvd not showing as dic in xmd but showing in file manager in hantoolbox

**Comment by PS3Xploit** [comment]
FUCK OFF!!

THIS IS NOT AN ISSUE!!

STOP BEING A DIRTY PIRATE!!!

POST A REAL ISSUE!!!

DOES THE FUCKING THING MOUNT?? THE ANSWER IS YES!!!!
